#![allow(clippy::expect_used, clippy::panic, clippy::unwrap_used)]
//! **The M4 flagship gate.** One frozen, checksummed incident corpus; one `taint(S)` call; every
//! standing answer database-wide equal to a world that never ingested S; the two-section
//! RecallPlan naming the suspended account first; untainted branches and bystander tenants
//! untouched; a second taint composing; and the taint path killed at every seam without ever
//! half-healing. `docs/M4-TAINT.md` is the contract. This gate runs in CI from this phase forever.

use loom_core::SourceRef;
use mutiny_incident::corpus::{self, hex, Corpus};
use mutiny_incident::host::{Host, HostPaths};
use mutiny_taint::{TaintFaults, TaintSeam};
use schweep_log::record::Record;
use schweep_log::{FaultInjector, Log, SyncPolicy};
use schweep_zset::Value;
use std::collections::BTreeSet;

// ---- the frozen incident corpus and its expectations, pinned by content address --------------

const EXPECTED_POISONED: &str = include_str!("../fixtures/expected-poisoned-answers.txt");
const EXPECTED_REPORT: &str = include_str!("../fixtures/expected-recall-report.txt");
const EXPECTED_HEALED: &str = include_str!("../fixtures/expected-healed-answers.txt");
const EXPECTED_SECOND_REPORT: &str = include_str!("../fixtures/expected-second-recall-report.txt");
const EXPECTED_HEALED_BOTH: &str = include_str!("../fixtures/expected-healed-both-answers.txt");

/// BLAKE3 of every committed fixture. A mismatch is a corpus drift, and it is loud: the corpus is
/// never regenerated by the code it tests.
const PINS: [(&str, &str, &str); 6] = [
    ("incident-corpus.tsv", corpus::CORPUS, PIN_CORPUS),
    (
        "expected-poisoned-answers.txt",
        EXPECTED_POISONED,
        PIN_POISONED,
    ),
    ("expected-recall-report.txt", EXPECTED_REPORT, PIN_REPORT),
    ("expected-healed-answers.txt", EXPECTED_HEALED, PIN_HEALED),
    (
        "expected-second-recall-report.txt",
        EXPECTED_SECOND_REPORT,
        PIN_SECOND_REPORT,
    ),
    (
        "expected-healed-both-answers.txt",
        EXPECTED_HEALED_BOTH,
        PIN_HEALED_BOTH,
    ),
];
const PIN_CORPUS: &str = "3dbda370a8c4233bc88944635fd7e1e2982e61fed8bb7ed93256e13e5ec956f8";
const PIN_POISONED: &str = "e01d8f3896f8d9952f2db6c8b9f633b2178cc59e14782317f85c8053d1ab0636";
const PIN_REPORT: &str = "1391784ad3b43e47d28c4c7f1b3c3058e22dae2140b74e8ccb708d06965de18a";
const PIN_HEALED: &str = "8cf261a212f74c3f65fe08e20289dfc0980252b0e37577ee53e0ad3cc8bc6f1c";
const PIN_SECOND_REPORT: &str = "715700e63e0d2010b0a36c9758b60568d47efa359cdad5fa53da6c79c12d662c";
const PIN_HEALED_BOTH: &str = "4364c9001c37c8f5dc6a2510efc5c4605cc62f915b1d67cb8440d8544f0da852";

fn poison() -> SourceRef {
    SourceRef::new("web", "scraped-page-77")
}

fn second_poison() -> SourceRef {
    SourceRef::new("web", "scraped-page-91")
}

struct World {
    _dirs: (tempfile::TempDir, tempfile::TempDir),
    paths: HostPaths,
    corpus: Corpus,
}

fn world() -> World {
    let corpus = corpus::parse(corpus::CORPUS).expect("the frozen corpus parses");
    let storage = tempfile::tempdir().expect("storage dir");
    let compute = tempfile::tempdir().expect("compute dir");
    let paths = HostPaths {
        storage: storage.path().to_path_buf(),
        compute: compute.path().to_path_buf(),
    };
    World {
        _dirs: (storage, compute),
        paths,
        corpus,
    }
}

/// The corpus-declared downstream rows of the given sources — the gate's independent knowledge of
/// the contamination, written by hand in the fixture, never derived from taint code.
fn declared_downstream(
    corpus: &Corpus,
    sources: &[&SourceRef],
) -> BTreeSet<(String, String, String)> {
    let mut rows = BTreeSet::new();
    for source in sources {
        let key = format!("{}:{}", source.system, source.record_id);
        rows.extend(
            corpus
                .downstream
                .get(&key)
                .unwrap_or_else(|| panic!("corpus declares downstream of {key}"))
                .iter()
                .cloned(),
        );
    }
    rows
}

/// **The independent oracle: the world that never ingested S.** Built from the corpus's own
/// downstream declarations by omitting those writes before ingestion — the M1-style recompute
/// control. It runs no taint code and holds no ledger; its standing answers are the definition of
/// healed.
fn oracle_answers(corpus: &Corpus, sources: &[&SourceRef]) -> String {
    let omit = declared_downstream(corpus, sources);
    let mut oracle = corpus.clone();
    oracle.commits.retain(|commit| {
        !omit.contains(&(
            commit.branch.clone(),
            commit.table.clone(),
            commit.key.clone(),
        ))
    });
    // The executed action is justified by a claim that never exists in this world; the world
    // without S never suspends the account. Standing answers do not include the action ledger.
    oracle.actions.clear();
    let storage = tempfile::tempdir().expect("oracle storage");
    let compute = tempfile::tempdir().expect("oracle compute");
    let paths = HostPaths {
        storage: storage.path().to_path_buf(),
        compute: compute.path().to_path_buf(),
    };
    let host = Host::build(&paths, &oracle).expect("oracle world builds");
    host.standing_answers().expect("oracle answers render")
}

/// **The cross-plane instrument.** Verifies from the live host that no plane still holds a
/// declared-downstream row: the payload circuits, the derivation relation, the recomputed
/// rollups, and every branch's semantic operators. Returns every violation it finds.
fn every_plane_heals(
    host: &Host,
    omit: &BTreeSet<(String, String, String)>,
) -> Result<(), Vec<String>> {
    let mut violations = Vec::new();

    let payload = [
        ("claims_current", corpus::CLAIMS),
        ("telemetry_current", corpus::TELEMETRY),
    ];
    for (query, table) in payload {
        for row in host.standing_rows(query).expect("standing rows") {
            let (Some(Value::Str(key)), Some(Value::Str(branch))) = (row.get(0), row.get(1)) else {
                violations.push(format!("{query}: malformed row"));
                continue;
            };
            if omit.contains(&(branch.clone(), table.to_owned(), key.clone())) {
                violations.push(format!("{query}: {branch}/{table}/{key} is still standing"));
            }
        }
    }

    for row in host.standing_rows("derivation_current").expect("edges") {
        let (Some(Value::Str(branch)), Some(Value::Str(table)), Some(Value::Str(row_key))) =
            (row.get(1), row.get(2), row.get(3))
        else {
            violations.push("derivation_current: malformed row".to_owned());
            continue;
        };
        if omit
            .iter()
            .any(|(b, t, k)| b == branch && t == table && hex(k.as_bytes()) == *row_key)
        {
            violations.push(format!(
                "derivation_current: edge for {branch}/{table}/{row_key} survived"
            ));
        }
    }

    // The rollups must equal a recomputation from the current payload rows — one plane cannot
    // heal while another keeps the stale aggregate.
    let mut expected_cost: std::collections::BTreeMap<String, (i64, i64)> = Default::default();
    for row in host.standing_rows("telemetry_current").expect("telemetry") {
        let (Some(Value::Str(branch)), Some(Value::Int(cost))) = (row.get(1), row.get(3)) else {
            continue;
        };
        let slot = expected_cost.entry(branch.clone()).or_insert((0, 0));
        slot.0 += cost;
        slot.1 += 1;
    }
    let mut actual_cost: std::collections::BTreeMap<String, (i64, i64)> = Default::default();
    for row in host.standing_rows("cost_by_branch").expect("rollup") {
        let (Some(Value::Str(branch)), Some(Value::Int(total)), Some(Value::Int(events))) =
            (row.get(0), row.get(1), row.get(2))
        else {
            continue;
        };
        actual_cost.insert(branch.clone(), (*total, *events));
    }
    if expected_cost != actual_cost {
        violations.push(format!(
            "cost_by_branch: rollup {actual_cost:?} does not equal recomputation {expected_cost:?}"
        ));
    }

    let omitted_telemetry: BTreeSet<(&String, &String)> = omit
        .iter()
        .filter(|(_, table, _)| table == corpus::TELEMETRY)
        .map(|(branch, _, key)| (branch, key))
        .collect();
    for branch in host.branches() {
        let token = &host.tokens[branch];
        let id = loom_core::BranchId::new(branch.as_str());
        let hits = host
            .agent
            .answer(token, &id, mutiny_incident::host::TOPK_QUERY)
            .expect("semantic answer");
        for hit in hits {
            if omitted_telemetry.contains(&(branch, &hit.key)) {
                violations.push(format!(
                    "semantic:{branch}: {key} is still ranked",
                    key = hit.key
                ));
            }
        }
        let summaries = host
            .agent
            .group_summaries(token, &id, mutiny_incident::host::GROUPS_QUERY)
            .expect("group summaries");
        for group in summaries {
            for member in &group.member_keys {
                if omitted_telemetry.contains(&(branch, member)) {
                    violations.push(format!("groups:{branch}: {member} is still grouped"));
                }
            }
        }
    }

    if violations.is_empty() {
        Ok(())
    } else {
        Err(violations)
    }
}

// ---- the gate ---------------------------------------------------------------------------------

#[test]
fn the_corpus_and_its_expectations_are_frozen() {
    let mut drifted = Vec::new();
    for (name, content, pin) in PINS {
        let actual = blake3::hash(content.as_bytes()).to_hex().to_string();
        if actual != pin {
            drifted.push(format!("{name}: pinned {pin}, actual {actual}"));
        }
    }
    assert!(
        drifted.is_empty(),
        "fixtures drifted:\n{}",
        drifted.join("\n")
    );
}

#[test]
fn standing_answers_are_current_before_the_incident() {
    let world = world();
    let host = Host::build(&world.paths, &world.corpus).expect("host builds");
    let answers = host.standing_answers().expect("answers render");
    assert_eq!(answers, EXPECTED_POISONED);
    // The poison is standing and believed: the corpus is a real incident, not a clean room.
    assert!(answers.contains("evt-a1"));
    assert!(answers.contains("(\"user-4471\", 2)"));
}

#[test]
fn healed_world_equals_the_never_ingested_oracle() {
    let world = world();
    let mut host = Host::build(&world.paths, &world.corpus).expect("host builds");
    host.taint(&poison()).expect("taint runs");
    let healed = host.standing_answers().expect("answers render");
    assert_eq!(healed, EXPECTED_HEALED);
    let oracle = oracle_answers(&world.corpus, &[&poison()]);
    assert_eq!(
        healed, oracle,
        "every standing answer database-wide must be byte-identical to the world that never \
         ingested web:scraped-page-77"
    );
}

#[test]
fn the_recall_report_names_the_suspended_account_first() {
    let world = world();
    let mut host = Host::build(&world.paths, &world.corpus).expect("host builds");
    let outcome = host.taint(&poison()).expect("taint runs");
    let report = outcome.report.to_string();
    assert_eq!(report, EXPECTED_REPORT);
    let cannot = report
        .find("CANNOT BE UNDONE")
        .expect("the report says what it cannot undo");
    let healed = report
        .find("ALREADY HEALED")
        .expect("the report says what the engine already did");
    assert!(
        cannot < healed,
        "the suspended account must come before the healed writes"
    );
    assert!(report.contains("okta:suspend:user-4471"));
    assert!(report.contains("identity.reinstate_account"));
    assert_eq!(
        outcome.resolution_rounds, 2,
        "the two-hop claim resolves transitively"
    );
    assert_eq!(outcome.resolved, 4);
}

#[test]
fn untainted_branches_and_bystander_tenants_are_unaffected() {
    let world = world();
    let mut host = Host::build(&world.paths, &world.corpus).expect("host builds");

    let bystander_world = world_named();
    let bystander = Host::build(&bystander_world.paths, &bystander_world.corpus)
        .expect("bystander tenant builds");
    let bystander_before = bystander.standing_answers().expect("bystander answers");

    let before = host.standing_answers().expect("answers render");
    let bystander_branch_before = lines_touching(&before, &["sess-b", "acct-7"]);

    host.taint(&poison()).expect("taint runs");

    let after = host.standing_answers().expect("answers render");
    let bystander_branch_after = lines_touching(&after, &["sess-b", "acct-7"]);
    assert_eq!(
        bystander_branch_before, bystander_branch_after,
        "the untainted branch's answers must be byte-identical before and after"
    );

    let bystander_after = bystander.standing_answers().expect("bystander answers");
    assert_eq!(
        bystander_before, bystander_after,
        "a bystander tenant's world must be untouched"
    );
}

fn world_named() -> World {
    world()
}

fn lines_touching(answers: &str, needles: &[&str]) -> String {
    answers
        .lines()
        .filter(|line| needles.iter().any(|needle| line.contains(needle)))
        .collect::<Vec<_>>()
        .join("\n")
}

#[test]
fn a_second_taint_composes_and_the_report_is_regenerable() {
    let world = world();
    let mut host = Host::build(&world.paths, &world.corpus).expect("host builds");
    host.taint(&poison()).expect("first taint");
    let second = host.taint(&second_poison()).expect("second taint");
    assert_eq!(second.report.to_string(), EXPECTED_SECOND_REPORT);

    let healed = host.standing_answers().expect("answers render");
    assert_eq!(healed, EXPECTED_HEALED_BOTH);
    let oracle = oracle_answers(&world.corpus, &[&poison(), &second_poison()]);
    assert_eq!(
        healed, oracle,
        "two taints must compose to the world that never ingested either source"
    );

    // Taints are not one-shot, and neither are their reports: a re-taint of the healed source
    // resolves nothing new and regenerates the same plan from the ledger.
    let regenerated = host.taint(&poison()).expect("re-taint");
    assert_eq!(regenerated.resolved, 0);
    assert_eq!(regenerated.report.to_string(), EXPECTED_REPORT);
}

#[test]
fn every_plane_heals_from_one_taint_call() {
    let world = world();
    let mut host = Host::build(&world.paths, &world.corpus).expect("host builds");
    let omit = declared_downstream(&world.corpus, &[&poison()]);

    // The instrument must see the poison before the heal — an instrument that cannot fail is not
    // an instrument.
    assert!(
        every_plane_heals(&host, &omit).is_err(),
        "the cross-plane instrument must detect the standing poison before the taint"
    );

    host.taint(&poison()).expect("taint runs");
    if let Err(violations) = every_plane_heals(&host, &omit) {
        panic!("planes did not heal from one taint call: {violations:?}");
    }
}

// ---- teeth: the gate has proven it can fail, in the direction that lies pleasantly -----------

/// **Tooth A.** One derivation edge of the multi-source claim is dropped at ingest (a host-side
/// filter; the production capture cannot drop one without failing MD-2 R5's audit). The taint
/// then reports clean while the world still differs from the oracle — and the catching
/// instruments are `healed_world_equals_the_never_ingested_oracle`'s byte comparison and the
/// cross-plane instrument, both of which must detect the miss.
#[test]
fn tooth_a_a_dropped_derivation_edge_cannot_pass_the_oracle_gate() {
    let mut corpus = corpus::parse(corpus::CORPUS).expect("corpus parses");
    let commit = corpus
        .commits
        .iter_mut()
        .find(|commit| commit.key == "clm-1")
        .expect("the multi-source claim");
    assert_eq!(commit.sources.len(), 2, "clm-1 is the multi-source claim");
    commit.sources.retain(|source| source.system != "web");

    let storage = tempfile::tempdir().expect("storage");
    let compute = tempfile::tempdir().expect("compute");
    let paths = HostPaths {
        storage: storage.path().to_path_buf(),
        compute: compute.path().to_path_buf(),
    };
    let mut host = Host::build(&paths, &corpus).expect("host builds");
    let outcome = host.taint(&poison()).expect("taint runs");

    // The lie is in the pleasant direction: the report says these claims are clean.
    let report = outcome.report.to_string();
    assert!(
        !report.contains(&hex("clm-1".as_bytes())),
        "with the edge dropped, taint must miss clm-1 — that is the failure this tooth injects"
    );
    assert!(!report.contains(&hex("clm-2".as_bytes())));

    // And the instruments catch it.
    let healed = host.standing_answers().expect("answers render");
    let oracle = oracle_answers(&corpus, &[&poison()]);
    assert_ne!(
        healed, oracle,
        "the oracle byte-comparison must catch the world that still contains the claim"
    );
    let omit = declared_downstream(&corpus, &[&poison()]);
    let violations = every_plane_heals(&host, &omit).expect_err("the instrument must fire");
    assert!(
        violations
            .iter()
            .any(|violation| violation.contains("clm-1")),
        "the violation must name the missed claim: {violations:?}"
    );
}

/// **Tooth B.** A retraction that skips every plane but one — only the claims channel is
/// retracted, by hand — and the cross-plane instrument `every_plane_heals_from_one_taint_call`
/// must catch the planes left poisoned.
#[test]
fn tooth_b_a_skipped_plane_cannot_pass_the_cross_plane_gate() {
    let world = world();
    let mut host = Host::build(&world.paths, &world.corpus).expect("host builds");
    host.engine
        .retract_source(
            "acme/memory/claims",
            Some(corpus::CLAIMS),
            Some(
                "(claims.branch = 'sess-a' AND claims.claim_id = 'clm-1') OR \
                 (claims.branch = 'hyp-a' AND claims.claim_id = 'clm-2')",
            ),
        )
        .expect("the half-retraction seals");

    let omit = declared_downstream(&world.corpus, &[&poison()]);
    let violations = every_plane_heals(&host, &omit).expect_err("the instrument must fire");
    let text = violations.join("\n");
    assert!(
        text.contains("telemetry") && text.contains("derivation") && text.contains("semantic"),
        "every skipped plane must be named: {violations:?}"
    );
}

// ---- crash injection across the taint path ----------------------------------------------------

#[test]
fn a_taint_interrupted_at_every_seam_resumes_to_the_never_crashed_twin() {
    let seams = [
        TaintSeam::AfterResolve,
        TaintSeam::AfterJournal,
        TaintSeam::AfterVolatileHeal,
        TaintSeam::BetweenPayloadChannels,
        TaintSeam::BeforeDerivationRetraction,
        TaintSeam::BeforeReport,
    ];
    for seam in seams {
        let world = world();
        let mut host = Host::build(&world.paths, &world.corpus).expect("host builds");
        let mut faults = TaintFaults::planned(seam);
        let interrupted = host.taint_with_faults(&poison(), &mut faults);
        assert!(interrupted.is_err(), "seam {seam:?} must interrupt");
        assert_eq!(faults.fired(), Some(seam), "seam {seam:?} must have fired");

        // The process dies here. Everything volatile is lost; everything durable is on disk.
        drop(host);

        let mut recovered = Host::reopen(&world.paths, &world.corpus).expect("host reopens");
        let outcome = recovered
            .taint(&poison())
            .expect("the resumed taint completes");
        let answers = recovered.standing_answers().expect("answers render");
        assert_eq!(
            answers, EXPECTED_HEALED,
            "seam {seam:?}: the resumed world must equal the never-crashed twin"
        );
        assert_eq!(
            outcome.report.to_string(),
            EXPECTED_REPORT,
            "seam {seam:?}: the resumed report must equal the never-crashed twin's"
        );
        let omit = declared_downstream(&world.corpus, &[&poison()]);
        if let Err(violations) = every_plane_heals(&recovered, &omit) {
            panic!("seam {seam:?} half-healed: {violations:?}");
        }
    }
}

/// A crash **inside** the retraction itself: the negative batch is durably appended but the epoch
/// is not sealed. The batch is constructed at the log level with Schweep's own token derivation,
/// and the resumed taint must complete it — C11's pending-retraction path — without double
/// retraction.
#[test]
fn a_pending_mid_retraction_batch_is_completed_not_duplicated() {
    let world = world();
    let host = Host::build(&world.paths, &world.corpus).expect("host builds");
    let claims_rows: Vec<(schweep_zset::Row, i64)> = world
        .corpus
        .commits
        .iter()
        .filter(|commit| commit.key == "clm-1" || commit.key == "clm-2")
        .map(|commit| (commit.row.clone(), -1))
        .collect();
    assert_eq!(claims_rows.len(), 2);
    drop(host);

    // Reproduce the exact pending state a crash inside `retract_source` leaves behind.
    let catalog = corpus::catalog().expect("catalog");
    let mut faults = FaultInjector::inert();
    let mut log = Log::open(
        world.paths.compute.join("log"),
        catalog.clone(),
        &mut faults,
        SyncPolicy::Full,
    )
    .expect("the compute log reopens");
    let source = "acme/memory/claims";
    let target_epoch = log.sealed_epoch() + 1;
    let identity = Record::Append {
        source_id: source.to_owned(),
        dedup_token: String::new(),
        table: corpus::CLAIMS.to_owned(),
        entries: claims_rows.clone(),
    }
    .content_hash();
    let token = format!(
        "retract:{source}:{target_epoch}:{}:{identity:016x}",
        corpus::CLAIMS
    );
    log.append(source, corpus::CLAIMS, claims_rows, &token, &mut faults)
        .expect("the pending retraction batch lands");
    drop(log);

    let mut recovered = Host::reopen(&world.paths, &world.corpus).expect("host reopens");
    let outcome = recovered
        .taint(&poison())
        .expect("the resumed taint completes");
    let answers = recovered.standing_answers().expect("answers render");
    assert_eq!(
        answers, EXPECTED_HEALED,
        "the pending batch must be completed exactly once, never doubled"
    );
    assert_eq!(outcome.report.to_string(), EXPECTED_REPORT);
    let omit = declared_downstream(&world.corpus, &[&poison()]);
    if let Err(violations) = every_plane_heals(&recovered, &omit) {
        panic!("the completed pending retraction half-healed: {violations:?}");
    }
}
