//! The measured cost model behind `EXPLAIN STATE`'s byte column (I-10).
//!
//! **Every number here is in `testing/evidence/registry.json` with its artifact**, and the artifact —
//! `testing/evidence/c8-state-costs.json` — is regenerated by
//! `cargo run --release -p schweep-state --bin state-costs` and *checked by a test*. If redb's on-disk
//! layout changes, or the key codec changes, or somebody edits a number here to make a gate pass, the
//! evidence test fails.
//!
//! ## Why this is a floor and a presence check, not an estimate
//!
//! Three attempts, each corrected by a measurement:
//!
//! 1. Guessed constants (12 KiB per backend, 96 bytes per entry). The measurement said **1,056,768**
//!    and *67…205*: a hundredfold error and a threefold spread.
//! 2. A point estimate with a tolerance. Rejected: a per-entry cost depends on key width, and the
//!    frozen trait reports entries, not bytes.
//! 3. A measured *envelope*, floor and ceiling. The **ceiling gate broke it**: a shape with a
//!    480-character padding column reached 269 MB of state against a 36 MB ceiling. Key width is
//!    unbounded, so no per-entry constant can bound bytes from above.
//!
//! What survives is what can be true: a **floor** (every entry costs at least so much) and a
//! **presence** check (no entries means no footprint beyond the empty files). Both catch a report that
//! lies about state in either direction, which is the reconciliation gate's actual job.
//!
//! The first draft of this file guessed `12_288` bytes per backend and `96` per entry. The measurement
//! said **1,056,768** and *between 67 and 200* — a hundredfold error on the first and a threefold spread
//! on the second. Both numbers are now measured, and the spread is the interesting part:
//!
//! ```text
//!   an empty file:                           1,056,768 bytes (preallocated)
//!   1,500 entries:                             593,920 bytes — SMALLER than empty; it truncates
//!   key width 2, at scale:                      72 … 116 bytes per entry
//!   key width 4, at scale:                     164 … 205 bytes per entry
//! ```
//!
//! A per-entry cost depends on how wide the key is, and the frozen `StateBackend` trait reports
//! **entries, not bytes** (D-15) — deliberately, and it is frozen, so `EXPLAIN STATE` cannot ask how
//! wide the keys are without materialising them, which is precisely what state larger than RAM forbids.
//!
//! So the byte column is a **measured envelope**: a floor below the narrowest key and a ceiling above
//! the widest. That is weaker than a point estimate and much more honest than one, because the
//! reconciliation gate can then assert something true — *the actual footprint lies inside the
//! envelope* — instead of a point estimate hedged by a tolerance chosen to make it pass.
//!
//! **What a tighter model would take:** a trait that reports bytes, or one that reports the encoded
//! size of what it holds. That is an unfreezing of D-18, which is a decision above this file.

/// Bytes a redb backend may occupy over and above its entries.
///
/// **Measured: 1,056,768** — what a freshly created file preallocates. It is charged to the envelope's
/// *ceiling* and not to its floor, because redb truncates on commit: a backend holding a few thousand
/// entries measures **smaller** than an empty one. A join holds two stores and so pays this twice.
pub const BYTES_PER_BACKEND: u64 = 1_056_768;

/// The floor of the per-entry envelope. Below the narrowest measured figure (72 at scale).
///
/// The floor is per-entry *only*: see [`BYTES_PER_BACKEND`] for why no fixed overhead belongs here.
pub const BYTES_PER_ENTRY_LOW: u64 = 48;

/// The largest per-entry cost measured, for reporting. **Not a bound.**
///
/// It is not a bound because key width is unbounded: an operator's key is the join key followed by the
/// row's values (D-15), and a row may hold a string of any length. The ceiling gate proved this the hard
/// way — a shape with a 480-character padding column reached 269 MB of state against an envelope whose
/// ceiling was 36 MB, and the reconciliation gate failed, correctly.
///
/// So there is **no ceiling in the reconciliation**, and [`crate::Reconciliation`] documents what it
/// checks instead. Reporting a bound that arbitrary data can exceed would be worse than reporting none.
pub const BYTES_PER_ENTRY_TYPICAL_MAX: u64 = 205;

/// Bytes an in-memory backend occupies per entry.
///
/// Reported for completeness and **never reconciled**, because there is nothing to measure it against:
/// a `BTreeMap`'s footprint is the allocator's business. Publishing a byte figure for it that no test
/// can falsify is exactly what this project does not do, so `EXPLAIN STATE` on an in-memory backend
/// reports the envelope and the reconciliation reports "no bytes on disk" rather than a ratio.
pub const BYTES_PER_ENTRY_IN_MEMORY: u64 = 64;
